### ISSUE TITLE
Move it as another `it` 

### ISSUE THREAD

**Issue by Tom-OriginStorage** [ChainUp-Cloud/ChainUpAggregator#7]
https://github.com/ChainUp-Cloud/ChainUpAggregator/blob/61990e973d8ed08466afb778549bf5dbad5cb085/test/Aggregator.ts#L499

This has nothing to do with staking but `LidoController`, should not be here

**Comment by Tom-OriginStorage** [comment]
This should test if `aggregator` is removed from the `allowList`, `stake` should no longer work

**Comment by derricktan23** [comment]
fixed alongside fix #6
